export enum Categories {
    REFACTORING = 'REFACTORING',
    REMOVE = 'REMOVE',
    TEST = 'TEST',
    SIMPLIFY = 'SIMPLIFY',
    TOOLS = 'TOOLS',
    SMALL_STEPS = 'SMALL_STEPS',
    OUTSIDE_THE_BOX = 'OUTSIDE_THE_BOX',
    CRAZY = 'CRAZY'
}
